### ISSUE TITLE
Implement bifunctor

### ISSUE THREAD

**Issue by briancavalier** [briancavalier/creed#33]
There's been some recent updates to https://github.com/fantasyland/fantasy-land/pull/137, and it looks like the bifunctor spec is mostly stable.

The implementation seems like it would be quite simple.

**Comment by bergus** [comment]
Hm, that's exactly the thing my `Action` class was not capable of doing. Would I need `handle` to be passed to `tryCall` as a function parameter? I'll go figure.
Interestingly, in the end the `handle` actually is the only thing distinguishing [map](https://github.com/bergus/creed/blob/cancellation/src/map.js) from [chain](https://github.com/bergus/creed/blob/cancellation/src/chain.js)…

**Comment by briancavalier** [comment]
I'll probably send a PR for this on master, so we can see how it looks.
